### ISSUE TITLE
Tango needs access to docker socket and volumes for vmms/localDocker.py

### ISSUE THREAD

**Issue by bobbens** [autolab/autolab-oneclick#15]
I was unable to get Tango working out of the box. After quite a bit of debugging and digging I found the changes I made below worked, although they are fairly hacky.

The Tango vmms/localDocker.py requires you to mount /var/run/docker.sock to the docker container so it can use the docker command on the host (rather unsafe though).  Furthermore, the `autograding_image` seems to mount `/opt/TangoService/Tango/volumes`, however, this image is run on the host and the path is for the container. This can be "fixed" by creating the directory `/opt/TangoService/Tango/volumes` and mounting it on the container. This can by modifying the docker-compose.yaml to be the following (the part about volumes):
```
tango:
  build: ./Tango
  command: sh start.sh
  ports:
    - '8600:8600'
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/TangoService/Tango/volumes:/opt/TangoService/Tango/volumes
```

 I would like to know if I am overlooking anything or if there is a more simple way to handle this.
